services:
  - type: web
    name: f1-crawler
    runtime: python
    buildCommand: "pip install -r requirements.txt && python scraper.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
